### ISSUE TITLE
mongoDB connection fails on node 8

### ISSUE THREAD

**Issue by Sirius-A** [Sirius-A/sv-restaurant-zug-bot#31]
Heroku log:
~~~
/app/node_modules/mongodb/lib/utils.js:123
2017-07-18T14:09:14.406391+00:00 app[worker.1]:     process.nextTick(function() { throw err; });
2017-07-18T14:09:14.406392+00:00 app[worker.1]:                                   ^
2017-07-18T14:09:14.406393+00:00 app[worker.1]: 
2017-07-18T14:09:14.406394+00:00 app[worker.1]: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
2017-07-18T14:09:14.406394+00:00 app[worker.1]:     at /app/app/app.js:125:45
2017-07-18T14:09:14.406395+00:00 app[worker.1]:     at handleCallback (/app/node_modules/mongodb/lib/utils.js:120:56)
2017-07-18T14:09:14.406396+00:00 app[worker.1]:     at /app/node_modules/mongodb/lib/collection.js:1417:5
2017-07-18T14:09:14.406396+00:00 app[worker.1]:     at handleCallback (/app/node_modules/mongodb/lib/utils.js:120:56)
2017-07-18T14:09:14.406397+00:00 app[worker.1]:     at /app/node_modules/mongodb/lib/cursor.js:682:5
2017-07-18T14:09:14.406397+00:00 app[worker.1]:     at handleCallback (/app/node_modules/mongodb-core/lib/cursor.js:171:5)
2017-07-18T14:09:14.406398+00:00 app[worker.1]:     at nextFunction (/app/node_modules/mongodb-core/lib/cursor.js:682:5)
2017-07-18T14:09:14.406399+00:00 app[worker.1]:     at /app/node_modules/mongodb-core/lib/cursor.js:593:7
2017-07-18T14:09:14.406399+00:00 app[worker.1]:     at queryCallback (/app/node_modules/mongodb-core/lib/cursor.js:232:18)
2017-07-18T14:09:14.406400+00:00 app[worker.1]:     at /app/node_modules/mongodb-core/lib/connection/pool.js:469:18
2017-07-18T14:09:14.406400+00:00 app[worker.1]:     at _combinedTickCallback (internal/process/next_tick.js:95:7)
2017-07-18T14:09:14.406401+00:00 app[worker.1]:     at process._tickCallback (internal/process/next_tick.js:161:9)
~~~

**Comment by Sirius-A** [comment]
Node 8 was not the problem. Just a error in a query.

fixed in 7629ed2885196dd46a6d7576e9f2200b609f544a
